name: actividades

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
          
      - name: Cache Matplotlib Fonts
        uses: actions/cache@v3
        with:
          path: ~/.matplotlib
          key: font-cache-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Pre-build Matplotlib Cache
        run: python -c "import matplotlib.pyplot as plt; plt.figure(); plt.close()"
      - name: paso6 - Ejecutar script de la actividad 3
        run: python src/poo_2025/actividad_3.py

      - name: Verificar cambios en archivos antes del commit
        run: git status
      - name: Configurar usuario de Git
        run: |
          git config --global user.name "Bibiana Roman"
          git config --global user.email "bibiana.roman@est.iudigital.edu.co"

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entrega actividades
          commit_user_name: Bibiana Roman [GitHub Actions]
          commit_user_email: bibiana.roman@est.iudigital.edu.co
          commit_author: Bibiana Roman <bibiana.roman@est.iudigital.edu.co>
